# Generated by Django 6.0.5 on 2026-07-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsodevicemanagement",
            name="degraded_surfaces",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
