# Generated by Django 6.0.5 on 2026-06-02 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0001_initial"),
        ("netbox_routing", "0033_isis"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsoisisinterfacestate",
            name="isis_interface",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nso_interface_states",
                to="netbox_routing.isisinterface",
            ),
        ),
    ]
