# Generated by Django 6.0.4 on 2026-05-23 18:05

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0233_device_render_config_permission"),
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("netbox_nso_plugin", "0002_adapterconnection"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsodevicemanagement",
            name="auto_apply",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="NSOInterfaceState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("attribute", models.CharField(max_length=64)),
                ("status", models.CharField(default="unknown", max_length=32)),
                ("nso_value", models.TextField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("last_apply_at", models.DateTimeField(blank=True, null=True)),
                ("last_apply_error", models.JSONField(blank=True, null=True)),
                (
                    "interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="nso_states", to="dcim.interface"
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "NSO Interface State",
                "verbose_name_plural": "NSO Interface States",
                "ordering": ["interface", "attribute"],
                "unique_together": {("interface", "attribute")},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
