# Generated by Django 6.0.5 on 2026-07-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0002_nsodevicemanagement_degraded_surfaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsodevicemanagement",
            name="adapter_link_error",
            field=models.TextField(blank=True, default=""),
        ),
    ]
