# Generated by Django 6.0.5 on 2026-07-06 17:41

import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("netbox_nso_plugin", "0003_nsodevicemanagement_adapter_link_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsosnmpcommunitystate",
            name="vault_secret_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="nsosnmpcommunitystate",
            name="vault_secret_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsosnmpv3userstate",
            name="auth_protocol",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="nsosnmpv3userstate",
            name="group_name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="nsosnmpv3userstate",
            name="priv_protocol",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="nsosnmpv3userstate",
            name="vault_has_auth",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nsosnmpv3userstate",
            name="vault_has_priv",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="NSOVaultSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("kv_mount", models.CharField(default="network", max_length=128)),
                ("base_path", models.CharField(default="netbox/snmp", max_length=256)),
                ("enabled", models.BooleanField(default=True)),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "Vault Settings",
                "verbose_name_plural": "Vault Settings",
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
