# Generated by Django 6.0.5 on 2026-06-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0003_adapterconnection_auto_create_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsoisisinstancestate",
            name="area_auth_key",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="nsoisisinstancestate",
            name="domain_auth_key",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
