# Generated by Django 6.0.6 on 2026-07-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0004_nsosnmpcommunitystate_vault_secret_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsoroutepolicystate",
            name="unsupported_members",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
