# Generated by Django 6.0.4 on 2026-05-28 22:12

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0233_device_render_config_permission"),
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("netbox_nso_plugin", "0004_m12_interface_ip_state"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="nsointerfaceipstate",
            name="unique_nso_interface_ip_state",
        ),
        migrations.AlterField(
            model_name="nsointerfaceipstate",
            name="tags",
            field=taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterUniqueTogether(
            name="nsointerfaceipstate",
            unique_together={("interface", "address", "vrf")},
        ),
    ]
