# Generated by Django 6.0.5 on 2026-06-04 07:53

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0234_cablepath_nodes_index"),
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("netbox_nso_plugin", "0004_nsoisisinstancestate_area_auth_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NSOPlatformNedMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("ned_id", models.CharField(max_length=128)),
                (
                    "platform",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="nso_ned_mapping", to="dcim.platform"
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "NSO Platform-NED Mapping",
                "verbose_name_plural": "NSO Platform-NED Mappings",
                "ordering": ["platform"],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
