# Generated by Django 6.0.5 on 2026-06-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0005_nsoplatformnedmapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="adapterconnection",
            name="onboard_authgroup",
            field=models.CharField(default="network", max_length=128),
        ),
    ]
