# Generated by Django 6.0.6 on 2026-07-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0005_nsoroutepolicystate_unsupported_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsoisisinterfacestate",
            name="bfd_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
