# Generated by Django 6.0.4 on 2026-05-29 06:17

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("netbox_nso_plugin", "0005_m12_fix_ipstate_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="NSOSnmpSystemInfoState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("location", models.CharField(blank=True, default="", max_length=256)),
                ("contact", models.CharField(blank=True, default="", max_length=256)),
                ("status", models.CharField(default="unknown", max_length=32)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "management",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snmp_system_info_state",
                        to="netbox_nso_plugin.nsodevicemanagement",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "NSO SNMP System Info State",
                "verbose_name_plural": "NSO SNMP System Info States",
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="NSOSnmpCommunityState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("community_hash", models.CharField(max_length=64)),
                ("access", models.CharField(default="RO", max_length=8)),
                ("acl", models.CharField(blank=True, default="", max_length=128)),
                ("has_secret", models.BooleanField(default=True)),
                ("vault_ref", models.CharField(blank=True, default="", max_length=512)),
                ("status", models.CharField(default="unknown", max_length=32)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "management",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snmp_community_states",
                        to="netbox_nso_plugin.nsodevicemanagement",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "NSO SNMP Community State",
                "verbose_name_plural": "NSO SNMP Community States",
                "ordering": ["management", "community_hash"],
                "unique_together": {("management", "community_hash")},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="NSOSnmpHostState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("address", models.CharField(max_length=256)),
                ("version", models.CharField(default="v2c", max_length=8)),
                ("notify_type", models.CharField(default="trap", max_length=16)),
                ("port", models.PositiveIntegerField(blank=True, null=True)),
                ("community_hash", models.CharField(blank=True, default="", max_length=64)),
                ("status", models.CharField(default="unknown", max_length=32)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "management",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snmp_host_states",
                        to="netbox_nso_plugin.nsodevicemanagement",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "NSO SNMP Host State",
                "verbose_name_plural": "NSO SNMP Host States",
                "ordering": ["management", "address"],
                "unique_together": {("management", "address")},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="NSOSnmpV3UserState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("username", models.CharField(max_length=128)),
                ("has_auth_secret", models.BooleanField(default=False)),
                ("has_priv_secret", models.BooleanField(default=False)),
                ("vault_ref", models.CharField(blank=True, default="", max_length=512)),
                ("status", models.CharField(default="unknown", max_length=32)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "management",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snmp_v3_user_states",
                        to="netbox_nso_plugin.nsodevicemanagement",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "NSO SNMP V3 User State",
                "verbose_name_plural": "NSO SNMP V3 User States",
                "ordering": ["management", "username"],
                "unique_together": {("management", "username")},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
