# Generated by Django 6.0.6 on 2026-07-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0006_nsoisisinterfacestate_bfd_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsoisisinterfacestate",
            name="frr_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsoisisinterfacestate",
            name="frr_protection",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="nsoisisinstancestate",
            name="fast_reroute",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="nsoisisinstancestate",
            name="microloop_avoidance",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
