# Generated by Django 6.0.4 on 2026-05-29 08:10

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("netbox_nso_plugin", "0006_m11_snmp_state"),
        ("netbox_routing", "0029_community_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="NSOStaticRouteState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("status", models.CharField(default="unknown", max_length=32)),
                ("nso_vrf", models.CharField(blank=True, default="", max_length=128)),
                ("nso_prefix", models.CharField(blank=True, default="", max_length=64)),
                ("nso_next_hop", models.CharField(blank=True, default="", max_length=64)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("last_apply_at", models.DateTimeField(blank=True, null=True)),
                ("last_apply_error", models.TextField(blank=True, default="")),
                (
                    "management",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="static_route_states",
                        to="netbox_nso_plugin.nsodevicemanagement",
                    ),
                ),
                (
                    "static_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nso_states",
                        to="netbox_routing.staticroute",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "NSO Static Route State",
                "verbose_name_plural": "NSO Static Route States",
                "ordering": ["management", "static_route"],
                "unique_together": {("management", "static_route")},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
