# Generated by Django 6.0.5 on 2026-06-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0006_adapterconnection_onboard_authgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsodevicemanagement",
            name="onboard_steps",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsodevicemanagement",
            name="onboarded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
