# Generated by Django 6.0.6 on 2026-07-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0007_isis_frr_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsosnmphoststate",
            name="username",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
