# Generated by Django 6.0.5 on 2026-06-04 11:31

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("netbox_nso_plugin", "0007_nsodevicemanagement_onboard_steps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsodevicemanagement",
            name="manage_logging",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="NSOLoggingHostState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("address", models.CharField(max_length=256)),
                ("port", models.PositiveIntegerField(blank=True, null=True)),
                ("severity", models.CharField(blank=True, default="", max_length=32)),
                ("facility", models.CharField(blank=True, default="", max_length=32)),
                ("transport", models.CharField(blank=True, default="", max_length=16)),
                ("vrf", models.CharField(blank=True, default="", max_length=128)),
                ("source", models.CharField(blank=True, default="", max_length=256)),
                ("status", models.CharField(default="unknown", max_length=32)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "management",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logging_host_states",
                        to="netbox_nso_plugin.nsodevicemanagement",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "NSO Logging Host State",
                "verbose_name_plural": "NSO Logging Host States",
                "ordering": ["management", "address"],
                "unique_together": {("management", "address")},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
