# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Marcin Zieba <marcinpsk@gmail.com>
# Generated by Django 6.0.4 on 2026-05-29 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ipam", "0089_default_ordering_indexes"),
        ("netbox_nso_plugin", "0007_m10_static_route_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsointerfaceipstate",
            name="auto_assigned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nsointerfaceipstate",
            name="peer_state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="peer_back",
                to="netbox_nso_plugin.nsointerfaceipstate",
            ),
        ),
        migrations.AddField(
            model_name="nsointerfaceipstate",
            name="source_pool",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nso_ip_states_from_pool",
                to="ipam.prefix",
            ),
        ),
    ]
