# Generated by Django 6.0.6 on 2026-07-18

import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0008_snmp_host_v3_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="NSODerivedIntentTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                (
                    "sentinel",
                    models.CharField(
                        help_text=("Prefix marking an interface description as derived intent, for example '[auto]'."),
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        help_text=(
                            "Description pattern. It must begin with the sentinel and may use: "
                            "{peer_host}, {peer_iface}, {peer_site}, {peer_role}, {self_host}, {self_iface}."
                        ),
                        max_length=500,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Use this template for automatic interface description management.",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "NSO Derived Intent Template",
                "verbose_name_plural": "NSO Derived Intent Templates",
                "ordering": ["sentinel"],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
