# Generated by Django 6.0.5 on 2026-06-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0008_nsodevicemanagement_manage_logging_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsoisisinterfacestate",
            name="hello_auth_present",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nsoisisinterfacestate",
            name="hello_auth_type",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
