# Generated by Django 6.0.6 on 2026-07-18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0009_nsoderivedintenttemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsofailoversettings",
            name="active_probe_timeout",
            field=models.PositiveIntegerField(
                default=45,
                help_text="Seconds allowed for the active address to establish a cold NSO session.",
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)],
            ),
        ),
        migrations.AlterField(
            model_name="nsofailoversettings",
            name="probe_timeout",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Seconds allowed for an inactive-address flip probe — short, so a down path can't stall the loop.",
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)],
            ),
        ),
    ]
