# Generated by Django 6.0.5 on 2026-06-06 09:54

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("netbox_nso_plugin", "0009_nsoisisinterfacestate_hello_auth_present_and_more"),
        ("vpn", "0012_default_ordering_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsodevicemanagement",
            name="manage_l2",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="NSOL2SapState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("service_name", models.CharField(max_length=64)),
                ("service_type", models.CharField(blank=True, default="", max_length=16)),
                ("service_id", models.PositiveIntegerField(blank=True, null=True)),
                ("sap_id", models.CharField(max_length=64)),
                ("port", models.CharField(blank=True, default="", max_length=64)),
                ("outer_tag", models.PositiveIntegerField(blank=True, null=True)),
                ("inner_tag", models.PositiveIntegerField(blank=True, null=True)),
                ("status", models.CharField(default="unknown", max_length=32)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("last_apply_at", models.DateTimeField(blank=True, null=True)),
                ("last_apply_error", models.TextField(blank=True, default="")),
                (
                    "l2vpn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nso_l2_sap_states",
                        to="vpn.l2vpn",
                    ),
                ),
                (
                    "management",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="l2_sap_states",
                        to="netbox_nso_plugin.nsodevicemanagement",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "termination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nso_l2_sap_states",
                        to="vpn.l2vpntermination",
                    ),
                ),
            ],
            options={
                "verbose_name": "NSO L2 SAP State",
                "verbose_name_plural": "NSO L2 SAP States",
                "ordering": ["management", "service_name", "sap_id"],
                "unique_together": {("management", "service_name", "sap_id")},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
