# Generated by Django 6.0.5 on 2026-06-06 22:17

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0234_cablepath_nodes_index"),
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("netbox_nso_plugin", "0010_nsodevicemanagement_manage_l2_nsol2sapstate"),
    ]

    operations = [
        migrations.CreateModel(
            name="NSOLACPBundleState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("lag_id", models.PositiveIntegerField(blank=True, null=True)),
                ("min_links", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("system_priority", models.PositiveIntegerField(blank=True, null=True)),
                ("system_id", models.CharField(blank=True, default="", max_length=17)),
                ("timer", models.CharField(blank=True, default="", max_length=8)),
                ("admin_key", models.PositiveIntegerField(blank=True, null=True)),
                ("status", models.CharField(default="unknown", max_length=32)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("last_apply_at", models.DateTimeField(blank=True, null=True)),
                ("last_apply_error", models.TextField(blank=True, default="")),
                (
                    "interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nso_lacp_bundle_states",
                        to="dcim.interface",
                    ),
                ),
                (
                    "management",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lacp_bundle_states",
                        to="netbox_nso_plugin.nsodevicemanagement",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "NSO LACP Bundle State",
                "verbose_name_plural": "NSO LACP Bundle States",
                "ordering": ["management", "interface"],
                "unique_together": {("management", "interface")},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="NSOLACPMemberState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("mode", models.CharField(blank=True, default="", max_length=8)),
                ("port_priority", models.PositiveIntegerField(blank=True, null=True)),
                ("status", models.CharField(default="unknown", max_length=32)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("last_apply_at", models.DateTimeField(blank=True, null=True)),
                ("last_apply_error", models.TextField(blank=True, default="")),
                (
                    "interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nso_lacp_member_states",
                        to="dcim.interface",
                    ),
                ),
                (
                    "lag_bundle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nso_lacp_member_bundles",
                        to="dcim.interface",
                    ),
                ),
                (
                    "management",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lacp_member_states",
                        to="netbox_nso_plugin.nsodevicemanagement",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "NSO LACP Member State",
                "verbose_name_plural": "NSO LACP Member States",
                "ordering": ["management", "interface"],
                "unique_together": {("management", "interface")},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
