# Generated by Django 6.0.6 on 2026-07-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0010_nsofailoversettings_active_probe_timeout"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsolacpbundlestate",
            name="vpc_sensitive",
            field=models.BooleanField(default=False),
        ),
    ]
