# Generated by Django 6.0.6 on 2026-07-21 07:17

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        # Pin the OLDEST extras node the plugin already depends on (0001_initial's pin),
        # not the generating dev env's head — CI runs the minimum supported NetBox,
        # where a newer extras migration does not exist (NodeNotFoundError).
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("netbox_nso_plugin", "0011_nsolacpbundlestate_vpc_sensitive"),
    ]

    operations = [
        migrations.CreateModel(
            name="NSOLoggingLevelState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("console_severity", models.CharField(blank=True, default="", max_length=16)),
                ("monitor_severity", models.CharField(blank=True, default="", max_length=16)),
                ("module_severity", models.CharField(blank=True, default="", max_length=16)),
                ("status", models.CharField(default="unknown", max_length=32)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "management",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logging_level_state",
                        to="netbox_nso_plugin.nsodevicemanagement",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "NSO Logging Level State",
                "verbose_name_plural": "NSO Logging Level States",
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
