# Generated by Django 6.0.6 on 2026-07-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0012_nsologginglevelstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsologginglevelstate",
            name="last_apply_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsologginglevelstate",
            name="last_apply_error",
            field=models.TextField(blank=True, default=""),
        ),
    ]
