# Generated by Django 6.0.5 on 2026-06-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0012_m34_vlan_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nsoospfinstancestate",
            name="process_id",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="nsoospfinterfacestate",
            name="process_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
