# Generated by Django 6.0.5 on 2026-06-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0013_ospf_process_id_string"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsologginghoststate",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsosnmpcommunitystate",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsosnmphoststate",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsosnmpsysteminfostate",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsosnmpv3userstate",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
