# Generated by Django 6.0.5 on 2026-05-29 22:07

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("netbox_nso_plugin", "0013_m19_ospf_state"),
        ("netbox_routing", "0036_m20_redistribution"),
    ]

    operations = [
        migrations.CreateModel(
            name="NSORedistributionState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("dest_protocol", models.CharField(max_length=16)),
                ("dest_ref", models.CharField(blank=True, default="", max_length=128)),
                ("source_protocol", models.CharField(max_length=16)),
                ("source_ref", models.CharField(blank=True, default="", max_length=64)),
                ("route_map", models.CharField(blank=True, default="", max_length=128)),
                ("metric", models.PositiveIntegerField(blank=True, null=True)),
                ("metric_type", models.CharField(blank=True, default="", max_length=16)),
                ("status", models.CharField(default="unknown", max_length=32)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("last_apply_at", models.DateTimeField(blank=True, null=True)),
                ("last_apply_error", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "NSO Redistribution State",
                "verbose_name_plural": "NSO Redistribution States",
                "ordering": ["management", "dest_protocol", "dest_ref", "source_protocol"],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name="nsoroutepolicystate",
            name="netbox_nso_plugin_nsoroutepolicystate_management_family_name_uniq",
        ),
        migrations.AddField(
            model_name="nsoisisinstancestate",
            name="tags",
            field=taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AddField(
            model_name="nsoospfinstancestate",
            name="tags",
            field=taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AddField(
            model_name="nsoospfinterfacestate",
            name="tags",
            field=taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AddField(
            model_name="nsoroutepolicystate",
            name="tags",
            field=taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterField(
            model_name="nsoisisinstancestate",
            name="custom_field_data",
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name="nsoospfinstancestate",
            name="custom_field_data",
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name="nsoospfinterfacestate",
            name="custom_field_data",
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterField(
            model_name="nsoroutepolicystate",
            name="custom_field_data",
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AlterUniqueTogether(
            name="nsoroutepolicystate",
            unique_together={("management", "family", "object_name")},
        ),
        migrations.AddField(
            model_name="nsoredistributionstate",
            name="management",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="redistribution_states",
                to="netbox_nso_plugin.nsodevicemanagement",
            ),
        ),
        migrations.AddField(
            model_name="nsoredistributionstate",
            name="redistribution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nso_redistribution_states",
                to="netbox_routing.redistribution",
            ),
        ),
        migrations.AddField(
            model_name="nsoredistributionstate",
            name="tags",
            field=taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AlterUniqueTogether(
            name="nsoredistributionstate",
            unique_together={("management", "dest_protocol", "dest_ref", "source_protocol", "source_ref")},
        ),
    ]
