# Generated by Django 6.0.6 on 2026-07-21 17:18

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        # Pin the OLDEST extras node the plugin already depends on (0001_initial's pin),
        # not the dev environment's head: CI runs the minimum supported NetBox, where a
        # newer extras migration does not exist (NodeNotFoundError). See 0012's note.
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("netbox_nso_plugin", "0013_nsologginglevelstate_last_apply_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsodevicemanagement",
            name="adapter_incarnation",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="nsodevicemanagement",
            name="adapter_incarnation_born",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsodevicemanagement",
            name="reset_conflict_born",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsodevicemanagement",
            name="reset_pending_born",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsodevicemanagement",
            name="reset_pending_incarnation",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="NSOFamilyReadState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("family", models.CharField(max_length=64)),
                ("observed_outcome", models.CharField(blank=True, default="", max_length=32)),
                ("observed_reason", models.CharField(blank=True, default="", max_length=32)),
                ("observed_freshness", models.CharField(blank=True, default="", max_length=16)),
                ("observed_result", models.CharField(blank=True, default="", max_length=16)),
                ("observed_succeeded", models.BooleanField(blank=True, null=True)),
                ("observed_read_at", models.DateTimeField(blank=True, null=True)),
                ("observed_attempt_id", models.BigIntegerField(blank=True, null=True)),
                ("observed_incarnation", models.CharField(blank=True, default="", max_length=64)),
                ("observed_incarnation_born", models.DateTimeField(blank=True, null=True)),
                ("observed_epoch", models.IntegerField(blank=True, null=True)),
                ("applied_attempt_id", models.BigIntegerField(blank=True, null=True)),
                ("applied_incarnation", models.CharField(blank=True, default="", max_length=64)),
                (
                    "management",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_read_states",
                        to="netbox_nso_plugin.nsodevicemanagement",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "NSO Family Read State",
                "verbose_name_plural": "NSO Family Read States",
                "ordering": ["management", "family"],
                "unique_together": {("management", "family")},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
