# Generated by Django 6.0.5 on 2026-06-09 06:22

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0234_cablepath_nodes_index"),
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("ipam", "0089_default_ordering_indexes"),
        ("netbox_nso_plugin", "0014_nsologginghoststate_accepted_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NSOSVIState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("svi_type", models.CharField(default="svi", max_length=8)),
                ("status", models.CharField(default="unknown", max_length=32)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="nso_svi_states", to="dcim.interface"
                    ),
                ),
                (
                    "management",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="svi_states",
                        to="netbox_nso_plugin.nsodevicemanagement",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "vlan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nso_svi_states",
                        to="ipam.vlan",
                    ),
                ),
            ],
            options={
                "verbose_name": "NSO SVI State",
                "verbose_name_plural": "NSO SVI States",
                "ordering": ["management", "interface"],
                "unique_together": {("management", "interface")},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
