# Generated by Django 6.0.5 on 2026-05-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0014_m20_redistribution_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adapterconnection",
            name="url",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
