# Generated by Django 6.0.5 on 2026-06-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0015_nsosvistate"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsosvistate",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsosvistate",
            name="last_apply_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsosvistate",
            name="last_apply_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="nsosvistate",
            name="vrf",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
