# Generated by Django 6.0.5 on 2026-06-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0017_nsosubinterfacestate"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsovlanstate",
            name="device_name",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
