# Generated by Django 6.0.5 on 2026-06-09 17:51

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0234_cablepath_nodes_index"),
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("netbox_nso_plugin", "0018_nsovlanstate_device_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="NSOBFDInterfaceState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("min_tx", models.PositiveIntegerField(blank=True, null=True)),
                ("min_rx", models.PositiveIntegerField(blank=True, null=True)),
                ("multiplier", models.PositiveIntegerField(blank=True, null=True)),
                ("micro_bfd", models.BooleanField(default=False)),
                ("status", models.CharField(default="unknown", max_length=32)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("last_apply_at", models.DateTimeField(blank=True, null=True)),
                ("last_apply_error", models.TextField(blank=True, default="")),
                (
                    "interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="nso_bfd_states", to="dcim.interface"
                    ),
                ),
                (
                    "management",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bfd_states",
                        to="netbox_nso_plugin.nsodevicemanagement",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "NSO BFD State",
                "verbose_name_plural": "NSO BFD States",
                "ordering": ["management", "interface"],
                "unique_together": {("management", "interface")},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
