# Generated by Django 5.2.16 on 2026-08-25 18:15
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Marcin Zieba <marcinpsk@gmail.com>

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

PROMOTED_MODEL_NAMES = (
    "NSOBFDInterfaceState",
    "NSOInterfaceMtuState",
    "NSOL2SapState",
    "NSOLoggingLevelState",
    "NSORoutePolicyState",
    "NSOStaticRouteState",
    "NSOSubinterfaceState",
    "NSOSVIState",
    "NSOVLANState",
)


def normalize_deploying_rows(apps, _schema_editor):
    """Return rows with no durable Apply identity to operator-pending state."""
    from netbox_nso_plugin.intent_state import offline_mutation

    with offline_mutation():
        for model_name in PROMOTED_MODEL_NAMES:
            model = apps.get_model("netbox_nso_plugin", model_name)
            model.objects.filter(status="deploying").update(
                status="accepted",
                apply_attempt_id=None,
                last_apply_error="",
            )


class Migration(migrations.Migration):
    dependencies = [("netbox_nso_plugin", "0019_intent_deployment_control")]

    operations = [
        migrations.CreateModel(
            name="NSOApplyAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ("adapter_device_id", models.BigIntegerField(blank=True, null=True)),
                ("scope_revisions", models.JSONField(blank=True, default=dict)),
                ("selected", models.JSONField(blank=True, default=dict)),
                ("http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("response", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "NSO Apply Attempt",
                "verbose_name_plural": "NSO Apply Attempts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NSOIntentRevision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("scope", models.CharField(max_length=32)),
                ("revision", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "NSO Intent Revision",
                "verbose_name_plural": "NSO Intent Revisions",
                "ordering": ["device", "scope"],
            },
        ),
        migrations.AddField(
            model_name="nsointentoutboxstate",
            name="claim_revision",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsobfdinterfacestate",
            name="apply_attempt_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsointerfacemtustate",
            name="apply_attempt_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsol2sapstate",
            name="apply_attempt_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsologginglevelstate",
            name="apply_attempt_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsoroutepolicystate",
            name="apply_attempt_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsostaticroutestate",
            name="apply_attempt_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsosubinterfacestate",
            name="apply_attempt_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsosvistate",
            name="apply_attempt_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsovlanstate",
            name="apply_attempt_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(normalize_deploying_rows, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="nsobfdinterfacestate",
            index=models.Index(fields=["management", "status", "apply_attempt_id"], name="nso_bfd_apply_lookup"),
        ),
        migrations.AddIndex(
            model_name="nsointerfacemtustate",
            index=models.Index(fields=["management", "status", "apply_attempt_id"], name="nso_mtu_apply_lookup"),
        ),
        migrations.AddIndex(
            model_name="nsol2sapstate",
            index=models.Index(fields=["management", "status", "apply_attempt_id"], name="nso_l2sap_apply_lookup"),
        ),
        migrations.AddIndex(
            model_name="nsologginglevelstate",
            index=models.Index(fields=["management", "status", "apply_attempt_id"], name="nso_loglvl_apply_lookup"),
        ),
        migrations.AddIndex(
            model_name="nsoroutepolicystate",
            index=models.Index(fields=["management", "status", "apply_attempt_id"], name="nso_routepol_apply_lookup"),
        ),
        migrations.AddIndex(
            model_name="nsostaticroutestate",
            index=models.Index(fields=["management", "status", "apply_attempt_id"], name="nso_static_apply_lookup"),
        ),
        migrations.AddIndex(
            model_name="nsosubinterfacestate",
            index=models.Index(fields=["management", "status", "apply_attempt_id"], name="nso_subif_apply_lookup"),
        ),
        migrations.AddIndex(
            model_name="nsosvistate",
            index=models.Index(fields=["management", "status", "apply_attempt_id"], name="nso_svi_apply_lookup"),
        ),
        migrations.AddIndex(
            model_name="nsovlanstate",
            index=models.Index(fields=["management", "status", "apply_attempt_id"], name="nso_vlan_apply_lookup"),
        ),
        migrations.AddConstraint(
            model_name="nsobfdinterfacestate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "deploying"), _negated=True),
                    ("apply_attempt_id__isnull", False),
                    _connector="OR",
                ),
                name="nso_bfd_deploy_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="nsointerfacemtustate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "deploying"), _negated=True),
                    ("apply_attempt_id__isnull", False),
                    _connector="OR",
                ),
                name="nso_mtu_deploy_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="nsol2sapstate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "deploying"), _negated=True),
                    ("apply_attempt_id__isnull", False),
                    _connector="OR",
                ),
                name="nso_l2sap_deploy_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="nsologginglevelstate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "deploying"), _negated=True),
                    ("apply_attempt_id__isnull", False),
                    _connector="OR",
                ),
                name="nso_loglvl_deploy_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="nsoroutepolicystate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "deploying"), _negated=True),
                    ("apply_attempt_id__isnull", False),
                    _connector="OR",
                ),
                name="nso_routepol_deploy_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="nsostaticroutestate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "deploying"), _negated=True),
                    ("apply_attempt_id__isnull", False),
                    _connector="OR",
                ),
                name="nso_static_deploy_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="nsosubinterfacestate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "deploying"), _negated=True),
                    ("apply_attempt_id__isnull", False),
                    _connector="OR",
                ),
                name="nso_subif_deploy_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="nsosvistate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "deploying"), _negated=True),
                    ("apply_attempt_id__isnull", False),
                    _connector="OR",
                ),
                name="nso_svi_deploy_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="nsovlanstate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "deploying"), _negated=True),
                    ("apply_attempt_id__isnull", False),
                    _connector="OR",
                ),
                name="nso_vlan_deploy_attempt",
            ),
        ),
        migrations.AddField(
            model_name="nsoapplyattempt",
            name="management",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apply_attempts",
                to="netbox_nso_plugin.nsodevicemanagement",
            ),
        ),
        migrations.AddField(
            model_name="nsointentrevision",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="nso_intent_revisions", to="dcim.device"
            ),
        ),
        migrations.AddIndex(
            model_name="nsoapplyattempt",
            index=models.Index(fields=["management", "-created_at"], name="nso_apply_attempt_device"),
        ),
        migrations.AddConstraint(
            model_name="nsointentrevision",
            constraint=models.UniqueConstraint(fields=("device", "scope"), name="nso_intent_revision_key"),
        ),
    ]
