# Generated by Django 5.2.16 on 2026-08-27 08:44
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Marcin Zieba <marcinpsk@gmail.com>

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0020_nsoapplyattempt_nsointentrevision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsointentrevision",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsointentrevision",
            name="verified_fingerprint",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="nsointentrevision",
            name="verified_revision",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
