# Generated by Django 6.0.5 on 2026-08-30 04:04
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Marcin Zieba <marcinpsk@gmail.com>

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0234_cablepath_nodes_index"),
        ("netbox_nso_plugin", "0021_intent_revision_fingerprint"),
    ]

    operations = [
        migrations.CreateModel(
            name="NSOOwnershipManifest",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
                ),
                ("scope", models.CharField(max_length=32)),
                ("native_model_label", models.CharField(max_length=200)),
                ("native_key", models.JSONField()),
                ("ownership_state", models.CharField(default="owned", max_length=32)),
                ("deletion_authority", models.BooleanField(default=False)),
                ("acknowledged_lineage", models.JSONField(blank=True, default=list)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nso_ownership_manifest_entries",
                        to="dcim.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "NSO Ownership Manifest Entry",
                "verbose_name_plural": "NSO Ownership Manifest Entries",
                "ordering": ["device", "scope", "native_model_label", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device", "scope", "native_model_label", "native_key"),
                        name="nso_owner_manifest_identity",
                    )
                ],
            },
        ),
    ]
