# Generated by Django 6.0.5 on 2026-06-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0021_normalize_legacy_interface_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsobgppeerstate",
            name="device_base_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
