# Generated by Django 5.2.16 on 2026-08-27 08:48
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Marcin Zieba <marcinpsk@gmail.com>

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0022_ownership_manifest"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsointentoutboxentry",
            name="kind",
            field=models.CharField(default="ordinary", max_length=16),
        ),
    ]
