# Generated by Django 6.0.5 on 2026-06-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0022_nsobgppeerstate_device_base_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsoospfinstancestate",
            name="device_base_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="nsoospfinterfacestate",
            name="device_base_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="nsoredistributionstate",
            name="device_base_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
