# Generated by Django 6.0.5 on 2026-06-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0023_nsoospfinstancestate_device_base_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsoisisinstancestate",
            name="device_base_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="nsoisisinterfacestate",
            name="device_base_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
