# Generated by Django 5.2.16 on 2026-08-28 00:59
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Marcin Zieba <marcinpsk@gmail.com>

from django.db import migrations

BGP_STATE_MODELS = ("NSOBGPPeerState", "NSOBGPPeerTemplateState")


def reset_bgp_merge_bases(apps, _schema_editor):
    """Reset merge bases that used the superseded primary-key identity."""
    from netbox_nso_plugin.intent_state import offline_mutation

    with offline_mutation():
        for model_name in BGP_STATE_MODELS:
            model = apps.get_model("netbox_nso_plugin", model_name)
            model.objects.exclude(device_base_hash="").update(device_base_hash="")


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0023_outbox_contribution_kind"),
    ]

    operations = [
        migrations.RunPython(reset_bgp_merge_bases, migrations.RunPython.noop),
    ]
