# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Marcin Zieba <marcinpsk@gmail.com>
# Generated by Django 5.2.16 on 2026-08-28 12:44

import uuid

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0024_reset_bgp_merge_bases"),
    ]

    operations = [
        migrations.CreateModel(
            name="NSOProvisionTombstone",
            fields=[
                (
                    "provision_attempt_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("netbox_device_id", models.PositiveBigIntegerField(db_index=True)),
                ("nso_instance", models.CharField(max_length=255)),
                ("nso_device_name", models.CharField(max_length=255)),
                ("canonical_request", models.JSONField()),
                ("adapter_job_id", models.CharField(blank=True, default="", max_length=64)),
                ("adapter_device_id", models.BigIntegerField(blank=True, null=True)),
                ("state", models.CharField(default="open", max_length=16)),
                ("terminal_status", models.CharField(blank=True, default="", max_length=32)),
                ("terminal_evidence", models.JSONField(blank=True, null=True)),
                ("offboard_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "NSO Provision Tombstone",
                "verbose_name_plural": "NSO Provision Tombstones",
                "ordering": ["created_at", "provision_attempt_id"],
                "indexes": [
                    models.Index(fields=["state", "created_at"], name="nso_provision_sweep"),
                    models.Index(
                        fields=["netbox_device_id", "nso_instance", "nso_device_name"], name="nso_provision_identity"
                    ),
                ],
            },
        ),
    ]
