# Generated by Django 6.0.5 on 2026-06-10 11:20

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("netbox_nso_plugin", "0024_nsoisisinstancestate_device_base_hash_and_more"),
        ("netbox_routing", "0033_isis"),
    ]

    operations = [
        migrations.CreateModel(
            name="NSOBGPPeerTemplateState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("template_name", models.CharField(max_length=128)),
                ("remote_as_str", models.CharField(blank=True, default="", max_length=10)),
                ("status", models.CharField(default="unknown", max_length=32)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("last_apply_at", models.DateTimeField(blank=True, null=True)),
                ("last_apply_error", models.TextField(blank=True, default="")),
                ("device_base_hash", models.CharField(blank=True, default="", max_length=64)),
                (
                    "management",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bgp_peer_template_states",
                        to="netbox_nso_plugin.nsodevicemanagement",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nso_bgp_template_states",
                        to="netbox_routing.bgppeertemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "NSO BGP Peer Template State",
                "verbose_name_plural": "NSO BGP Peer Template States",
                "ordering": ["management", "template_name"],
                "unique_together": {("management", "template_name")},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
