# Copyright (C) 2026 Marcin Zieba <marcinpsk@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.8 on 2026-09-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0025_nsoownershipmanifest"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="nsoprovisiontombstone",
            name="nso_provision_sweep",
        ),
        migrations.AddIndex(
            model_name="nsoprovisiontombstone",
            index=models.Index(
                condition=models.Q(("state", "closed"), _negated=True),
                fields=["updated_at", "created_at", "provision_attempt_id"],
                name="nso_provision_sweep",
            ),
        ),
    ]
