# Generated by Django 5.2.16 on 2026-08-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0025_nsoprovisiontombstone"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsoownershipmanifest",
            name="native_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
