# Copyright (C) 2026 Marcin Zieba <marcinpsk@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.2 on 2026-08-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0025_nsoprovisiontombstone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NSOOwnershipManifest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("device_id", models.PositiveBigIntegerField(db_column="device_id", db_index=True)),
                ("scope", models.CharField(max_length=32)),
                ("native_model_label", models.CharField(max_length=200)),
                ("native_id", models.PositiveBigIntegerField()),
                ("native_key", models.JSONField()),
                ("state_model_label", models.CharField(max_length=200)),
                ("state_key", models.JSONField(blank=True, default=dict)),
                ("ownership_state", models.CharField(default="owned", max_length=32)),
                ("deletion_authority", models.BooleanField(default=False)),
                ("acknowledged_lineage", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "NSO Ownership Manifest Entry",
                "verbose_name_plural": "NSO Ownership Manifest Entries",
                "ordering": ["device_id", "scope", "native_model_label", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("device_id"),
                        models.F("scope"),
                        models.F("native_model_label"),
                        models.F("native_key"),
                        models.F("state_model_label"),
                        models.F("state_key"),
                        name="nso_owner_manifest_identity",
                    )
                ],
            },
        ),
    ]
