# SPDX-FileCopyrightText: 2026 Marcin Zieba <marcinpsk@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.5 on 2026-08-30 03:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0025_ownership_execution"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nsoownershipmanifest",
            options={"ordering": ["device_id", "scope", "native_model_label", "id"]},
        ),
        migrations.RenameField(
            model_name="nsoownershipmanifest",
            old_name="device",
            new_name="device_id",
        ),
    ]
