# Generated by Django 6.0.5 on 2026-06-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0025_nsobgppeertemplatestate"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsoswitchportstate",
            name="device_base_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
