# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Marcin Zieba <marcinpsk@gmail.com>
# Generated by Django 5.2.16 on 2026-08-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0025_nsoprovisiontombstone"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="nsoownershipmanifest",
            name="nso_owner_manifest_identity",
        ),
        migrations.AddField(
            model_name="nsoownershipmanifest",
            name="native_id",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AddField(
            model_name="nsoownershipmanifest",
            name="state_key",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="nsoownershipmanifest",
            name="state_model_label",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="nsoownershipmanifest",
            name="device",
            field=models.PositiveBigIntegerField(db_column="device_id", db_index=True),
        ),
        migrations.RenameField(
            model_name="nsoownershipmanifest",
            old_name="device",
            new_name="device_id",
        ),
        migrations.AlterModelOptions(
            name="nsoownershipmanifest",
            options={"ordering": ["device_id", "scope", "native_model_label", "id"]},
        ),
        migrations.AddConstraint(
            model_name="nsoownershipmanifest",
            constraint=models.UniqueConstraint(
                models.F("device_id"),
                models.F("scope"),
                models.F("native_model_label"),
                models.F("native_key"),
                models.F("state_model_label"),
                models.F("state_key"),
                name="nso_owner_manifest_identity",
            ),
        ),
        migrations.AddField(
            model_name="nsointerfaceipstate",
            name="allocation_kind",
            field=models.CharField(default="manual", max_length=16),
        ),
    ]
