# SPDX-FileCopyrightText: 2026 Marcin Zieba <marcinpsk@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.5 on 2026-08-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0026_ownership_device_identity"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="nsoownershipmanifest",
            constraint=models.UniqueConstraint(
                models.F("device_id"),
                models.F("scope"),
                models.F("native_model_label"),
                models.F("native_key"),
                models.F("state_model_label"),
                models.F("state_key"),
                name="nso_owner_manifest_identity",
            ),
        ),
    ]
