# Generated by Django 6.0.5 on 2026-06-11 05:38

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models

import netbox_nso_plugin.models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("netbox_nso_plugin", "0026_nsoswitchportstate_device_base_hash"),
        ("netbox_routing", "0047_ospfinstance_process_id_string"),
    ]

    operations = [
        migrations.CreateModel(
            name="NSOISISFlexAlgoState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("process_tag", models.CharField(blank=True, default="", max_length=128)),
                ("algo_id", models.PositiveSmallIntegerField()),
                ("metric_type", models.CharField(blank=True, default="", max_length=40)),
                ("priority", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("admin_group_exclude", models.CharField(blank=True, default="", max_length=200)),
                ("admin_group_include_any", models.CharField(blank=True, default="", max_length=200)),
                ("admin_group_include_all", models.CharField(blank=True, default="", max_length=200)),
                ("status", models.CharField(default="unknown", max_length=32)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("last_apply_at", models.DateTimeField(blank=True, null=True)),
                ("last_apply_error", models.TextField(blank=True, default="")),
                ("device_base_hash", models.CharField(blank=True, default="", max_length=64)),
                (
                    "isis_flex_algo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nso_flex_algo_states",
                        to="netbox_routing.isisflexalgo",
                    ),
                ),
                (
                    "management",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="isis_flex_algo_states",
                        to="netbox_nso_plugin.nsodevicemanagement",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "NSO IS-IS Flex-Algo State",
                "verbose_name_plural": "NSO IS-IS Flex-Algo States",
                "ordering": ["management", "process_tag", "algo_id"],
                "unique_together": {("management", "process_tag", "algo_id")},
            },
            bases=(netbox_nso_plugin.models._NSODeviceTabURLMixin, netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
