# Generated by Django 5.2.16 on 2026-08-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0026_nsoownershipmanifest_native_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="nsoownershipmanifest",
            name="nso_owner_manifest_identity",
        ),
        migrations.AddField(
            model_name="nsoownershipmanifest",
            name="state_key",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="nsoownershipmanifest",
            name="state_model_label",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="nsoownershipmanifest",
            name="device",
            field=models.PositiveBigIntegerField(db_column="device_id", db_index=True),
        ),
        migrations.AddConstraint(
            model_name="nsoownershipmanifest",
            constraint=models.UniqueConstraint(
                models.F("device"),
                models.F("scope"),
                models.F("native_model_label"),
                models.F("native_key"),
                models.F("state_model_label"),
                models.F("state_key"),
                name="nso_owner_manifest_identity",
            ),
        ),
    ]
