# Copyright (C) 2026 Marcin Zieba <marcinpsk@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 6.0.8 on 2026-09-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0026_provision_sweep_index"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="nsoprovisiontombstone",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "open")),
                fields=("nso_instance", "nso_device_name"),
                name="nso_open_provision_name",
            ),
        ),
    ]
