# Generated by Django 5.2.16 on 2026-08-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0027_remove_nsoownershipmanifest_nso_owner_manifest_identity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nsoownershipmanifest",
            options={"ordering": ["device_id", "scope", "native_model_label", "id"]},
        ),
        migrations.RemoveConstraint(
            model_name="nsoownershipmanifest",
            name="nso_owner_manifest_identity",
        ),
        migrations.RenameField(
            model_name="nsoownershipmanifest",
            old_name="device",
            new_name="device_id",
        ),
        migrations.AddConstraint(
            model_name="nsoownershipmanifest",
            constraint=models.UniqueConstraint(
                models.F("device_id"),
                models.F("scope"),
                models.F("native_model_label"),
                models.F("native_key"),
                models.F("state_model_label"),
                models.F("state_key"),
                name="nso_owner_manifest_identity",
            ),
        ),
    ]
