# Generated by Django 6.0.5 on 2026-06-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0027_nsoisisflexalgostate"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsoospfinstancestate",
            name="enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
