# Generated by Django 6.0.8 on 2026-09-23 10:30

from itertools import groupby

from django.db import migrations, models


def backfill_attempt_sequences(apps, schema_editor):
    tombstones = apps.get_model("netbox_nso_plugin", "NSOProvisionTombstone")
    alias = schema_editor.connection.alias
    rows = (
        tombstones.objects.using(alias)
        .order_by("nso_instance", "nso_device_name", "created_at", "provision_attempt_id")
        .iterator()
    )
    updates = []
    for _identity, siblings in groupby(rows, key=lambda row: (row.nso_instance, row.nso_device_name)):
        sequence = 0
        for _created_at, peers in groupby(siblings, key=lambda row: row.created_at):
            same_time = list(peers)
            sequence += len(same_time)
            if len(same_time) == 1:
                same_time[0].attempt_sequence = sequence
                updates.append(same_time[0])
    tombstones.objects.using(alias).bulk_update(updates, ["attempt_sequence"], batch_size=500)


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0027_open_provision_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsoprovisiontombstone",
            name="attempt_sequence",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.RunPython(backfill_attempt_sequences, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="nsoprovisiontombstone",
            constraint=models.UniqueConstraint(
                condition=models.Q(("attempt_sequence__gt", 0)),
                fields=("nso_instance", "nso_device_name", "attempt_sequence"),
                name="nso_provision_attempt_sequence",
            ),
        ),
    ]
