# Generated by Django 6.1 on 2026-09-25 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0028_nsoprovisiontombstone_attempt_sequence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsolacpbundlestate",
            name="apply_attempt_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsolacpmemberstate",
            name="apply_attempt_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nsoswitchportstate",
            name="apply_attempt_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="NSOSwitchingRootDeletion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("scope", models.CharField(max_length=16)),
                ("root_name", models.CharField(max_length=255)),
                ("event_version", models.BigIntegerField()),
                (
                    "management",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="netbox_nso_plugin.nsodevicemanagement"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("management", "scope", "root_name"), name="nso_switching_deletion_root"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("scope__in", ("lacp", "switchport"))), name="nso_switching_deletion_scope"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("root_name", ""), _negated=True), name="nso_switching_deletion_name"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("event_version__gt", 0)), name="nso_switching_deletion_version"
                    ),
                ],
            },
        ),
    ]
