# Generated by Django 6.0.5 on 2026-06-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0029_nsointerfacemtustate"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsodevicemanagement",
            name="sync_before_apply",
            field=models.BooleanField(default=True),
        ),
    ]
