# Generated by Django 6.1 on 2026-09-30 22:11

from django.db import migrations, models


def refuse_existing_manifests(apps, schema_editor):
    # A manifest without grant evidence has no valid grant_kind: remove old rows first (#1758).
    if apps.get_model("netbox_nso_plugin", "NSOOwnershipManifest").objects.exists():
        raise RuntimeError(
            "NSOOwnershipManifest rows exist: delete them before migrating, they carry no grant evidence"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0029_nsoswitchingrootdeletion"),
    ]

    operations = [
        migrations.RunPython(refuse_existing_manifests, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="nsobfdinterfacestate",
            options={"base_manager_name": "objects", "ordering": ["management", "interface"]},
        ),
        migrations.AlterModelOptions(
            name="nsobgppeerstate",
            options={
                "base_manager_name": "objects",
                "ordering": ["management", "asn_str", "vrf_name", "peer_address_str"],
            },
        ),
        migrations.AlterModelOptions(
            name="nsobgppeertemplatestate",
            options={"base_manager_name": "objects", "ordering": ["management", "template_name"]},
        ),
        migrations.AlterModelOptions(
            name="nsointerfaceipstate",
            options={"base_manager_name": "objects", "ordering": ["interface", "address", "vrf"]},
        ),
        migrations.AlterModelOptions(
            name="nsointerfacemtustate",
            options={"base_manager_name": "objects", "ordering": ["management", "interface"]},
        ),
        migrations.AlterModelOptions(
            name="nsointerfacestate",
            options={"base_manager_name": "objects", "ordering": ["interface", "attribute"]},
        ),
        migrations.AlterModelOptions(
            name="nsoisisflexalgostate",
            options={"base_manager_name": "objects", "ordering": ["management", "process_tag", "algo_id"]},
        ),
        migrations.AlterModelOptions(
            name="nsoisisinstancestate",
            options={"base_manager_name": "objects", "ordering": ["management", "process_tag"]},
        ),
        migrations.AlterModelOptions(
            name="nsoisisinterfacestate",
            options={"base_manager_name": "objects", "ordering": ["management", "interface", "af"]},
        ),
        migrations.AlterModelOptions(
            name="nsol2sapstate",
            options={"base_manager_name": "objects", "ordering": ["management", "service_name", "sap_id"]},
        ),
        migrations.AlterModelOptions(
            name="nsolacpbundlestate",
            options={"base_manager_name": "objects", "ordering": ["management", "interface"]},
        ),
        migrations.AlterModelOptions(
            name="nsolacpmemberstate",
            options={"base_manager_name": "objects", "ordering": ["management", "interface"]},
        ),
        migrations.AlterModelOptions(
            name="nsologginghoststate",
            options={"base_manager_name": "objects", "ordering": ["management", "address"]},
        ),
        migrations.AlterModelOptions(
            name="nsologginglevelstate",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="nsoospfinstancestate",
            options={"base_manager_name": "objects", "ordering": ["management", "process_id"]},
        ),
        migrations.AlterModelOptions(
            name="nsoospfinterfacestate",
            options={"base_manager_name": "objects", "ordering": ["management", "interface"]},
        ),
        migrations.AlterModelOptions(
            name="nsoredistributionstate",
            options={
                "base_manager_name": "objects",
                "ordering": ["management", "dest_protocol", "dest_ref", "source_protocol"],
            },
        ),
        migrations.AlterModelOptions(
            name="nsoroutepolicystate",
            options={"base_manager_name": "objects", "ordering": ["management", "family", "object_name"]},
        ),
        migrations.AlterModelOptions(
            name="nsosnmpcommunitystate",
            options={"base_manager_name": "objects", "ordering": ["management", "community_hash"]},
        ),
        migrations.AlterModelOptions(
            name="nsosnmphoststate",
            options={"base_manager_name": "objects", "ordering": ["management", "address"]},
        ),
        migrations.AlterModelOptions(
            name="nsosnmpsysteminfostate",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="nsosnmpv3userstate",
            options={"base_manager_name": "objects", "ordering": ["management", "username"]},
        ),
        migrations.AlterModelOptions(
            name="nsostaticroutestate",
            options={"base_manager_name": "objects", "ordering": ["management", "static_route"]},
        ),
        migrations.AlterModelOptions(
            name="nsosubinterfacestate",
            options={"base_manager_name": "objects", "ordering": ["management", "interface"]},
        ),
        migrations.AlterModelOptions(
            name="nsosvistate",
            options={"base_manager_name": "objects", "ordering": ["management", "interface"]},
        ),
        migrations.AlterModelOptions(
            name="nsoswitchportstate",
            options={"base_manager_name": "objects", "ordering": ["management", "interface"]},
        ),
        migrations.AlterModelOptions(
            name="nsovlanstate",
            options={"base_manager_name": "objects", "ordering": ["management", "vlan"]},
        ),
        migrations.AddField(
            model_name="nsoownershipmanifest",
            name="grant_kind",
            field=models.CharField(default="accept", max_length=32),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="NSOOwnershipAcquisition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("state_model_label", models.CharField(max_length=200)),
                ("state_id", models.PositiveBigIntegerField()),
                ("grant_kind", models.CharField(max_length=32)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("state_model_label", "state_id"), name="nso_owner_acquisition_identity"
                    )
                ],
            },
        ),
    ]
