# Generated by Django 6.1 on 2026-10-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0030_ownership_grants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nsolacpmemberstate",
            name="lag_bundle",
        ),
        migrations.AddField(
            model_name="nsolacpbundlestate",
            name="device_present",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="nsolacpbundlestate",
            name="observed_members",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
