# Generated by Django 6.0.5 on 2026-06-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0030_nsodevicemanagement_sync_before_apply"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsodevicemanagement",
            name="last_journaled_apply_job",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
