# Generated by Django 6.0.5 on 2026-06-15 13:01

from django.db import migrations, models


def _backfill_materialized_owner(apps, schema_editor):
    """Mark one materialized owner per (family, object_name) group for existing rows.

    Globally-deduped route-policy objects predate the per-device ownership model, so the
    shared NetBox object already holds SOME device's content but no row is flagged as the
    materialized owner.  The first device to import an object is the one that filled it,
    so pick the lowest-pk row in each group as the presumed owner.  Best-effort: an
    operator can re-point ownership to any device's version afterwards.
    """
    State = apps.get_model("netbox_nso_plugin", "NSORoutePolicyState")
    seen: set[tuple] = set()
    for row in State.objects.order_by("pk").iterator():
        key = (row.family, row.object_name)
        if key in seen:
            continue
        seen.add(key)
        if not row.is_materialized:
            row.is_materialized = True
            row.save(update_fields=["is_materialized"])


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0031_nsodevicemanagement_last_journaled_apply_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsoroutepolicystate",
            name="captured",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="nsoroutepolicystate",
            name="is_materialized",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(_backfill_materialized_owner, migrations.RunPython.noop),
    ]
