# Generated by Django 6.1 on 2026-10-06 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0032_require_case_sensitive_policy_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="NSOFamilyObservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("revision", models.BigIntegerField()),
                ("source_epoch", models.BigIntegerField()),
                ("digest", models.CharField(max_length=64)),
                ("coverage", models.JSONField()),
                ("document", models.JSONField()),
                ("observed_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(auto_now=True)),
                (
                    "read_state",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observation",
                        to="netbox_nso_plugin.nsofamilyreadstate",
                    ),
                ),
            ],
        ),
    ]
