# Generated by Django 6.0.5 on 2026-06-18 18:39

import django.core.validators
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("netbox_nso_plugin", "0033_rematerialise_route_map_structure"),
    ]

    operations = [
        migrations.CreateModel(
            name="NSOFailoverSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "primary_probe_interval",
                    models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)]),
                ),
                (
                    "oob_probe_interval",
                    models.PositiveIntegerField(default=360, validators=[django.core.validators.MinValueValidator(1)]),
                ),
                (
                    "failure_threshold",
                    models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
                ),
                (
                    "success_threshold",
                    models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
                ),
                (
                    "probe_timeout",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "probe_concurrency",
                    models.PositiveIntegerField(
                        default=8,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(64),
                        ],
                    ),
                ),
                (
                    "max_flips_per_tick",
                    models.PositiveIntegerField(
                        default=8,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(256),
                        ],
                    ),
                ),
                ("sync_from_after_switch", models.BooleanField(default=True)),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "Failover Settings",
                "verbose_name_plural": "Failover Settings",
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
