# Generated by Django 6.0.5 on 2026-06-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0034_nsofailoversettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsoredistributionstate",
            name="device_present",
            field=models.BooleanField(default=True),
        ),
    ]
