# Generated by Django 6.0.5 on 2026-06-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0035_nsoredistributionstate_device_present"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsoroutepolicystate",
            name="device_present",
            field=models.BooleanField(default=True),
        ),
    ]
