# Generated by Django 6.0.5 on 2026-06-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_nso_plugin", "0036_nsoroutepolicystate_device_present"),
    ]

    operations = [
        migrations.AddField(
            model_name="nsodevicemanagement",
            name="onboard_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="nsodevicemanagement",
            name="onboard_job_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="nsodevicemanagement",
            name="onboard_status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
