# Generated by Django 6.0.5 on 2026-06-22 19:56

import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("netbox_nso_plugin", "0037_nsodevicemanagement_onboard_error_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NSORoutePolicyObjectClass",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("family", models.CharField(max_length=32)),
                ("object_name", models.CharField(max_length=256)),
                ("mode", models.CharField(default="master", max_length=16)),
                ("source", models.CharField(default="operator", max_length=16)),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "NSO Route Policy Object Class",
                "verbose_name_plural": "NSO Route Policy Object Classes",
                "ordering": ["family", "object_name"],
                "unique_together": {("family", "object_name")},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
