# Generated by Django 6.0.5 on 2026-07-01 06:22

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0234_cablepath_nodes_index"),
        ("extras", "0138_customfieldchoiceset_choice_colors"),
        ("ipam", "0089_default_ordering_indexes"),
        ("netbox_nso_plugin", "0038_nsoroutepolicyobjectclass"),
    ]

    operations = [
        migrations.CreateModel(
            name="NSOLinkRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.CharField(blank=True, default="", max_length=200)),
                ("enabled", models.BooleanField(default=True)),
                ("link_type", models.CharField(default="p2p", max_length=16)),
                ("assign_ipv4", models.BooleanField(default=True)),
                ("assign_ipv6", models.BooleanField(default=False)),
                ("ipv4_pool_role", models.CharField(blank=True, default="", max_length=100)),
                ("ipv6_pool_role", models.CharField(blank=True, default="", max_length=100)),
                (
                    "ipv4_mask",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(32),
                        ],
                    ),
                ),
                (
                    "ipv6_mask",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(128),
                        ],
                    ),
                ),
                ("description_template", models.CharField(blank=True, default="", max_length=200)),
                ("igp", models.CharField(default="none", max_length=16)),
                ("isis_circuit_type", models.CharField(blank=True, default="", max_length=32)),
                ("isis_passive", models.BooleanField(default=False)),
                ("isis_metric", models.PositiveIntegerField(blank=True, null=True)),
                ("isis_process_tag", models.CharField(blank=True, default="", max_length=128)),
                ("ospf_area", models.CharField(blank=True, default="", max_length=64)),
                ("ospf_network_type", models.CharField(blank=True, default="", max_length=32)),
                ("ospf_passive", models.BooleanField(default=False)),
                ("ospf_cost", models.PositiveIntegerField(blank=True, null=True)),
                ("ospf_process_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "ipv4_pool_prefix",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nso_link_roles_v4",
                        to="ipam.prefix",
                    ),
                ),
                (
                    "ipv6_pool_prefix",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nso_link_roles_v6",
                        to="ipam.prefix",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "NSO Link Role",
                "verbose_name_plural": "NSO Link Roles",
                "ordering": ["name"],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="NSOLinkRoleAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                (
                    "cable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nso_link_role_assignments",
                        to="dcim.cable",
                    ),
                ),
                (
                    "interface",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nso_link_role_assignments",
                        to="dcim.interface",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="netbox_nso_plugin.nsolinkrole",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "NSO Link Role Assignment",
                "verbose_name_plural": "NSO Link Role Assignments",
                "ordering": ["role", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("cable__isnull", False)),
                        fields=("cable",),
                        name="nso_linkrole_unique_cable",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("interface__isnull", False)),
                        fields=("interface",),
                        name="nso_linkrole_unique_interface",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("cable__isnull", False), ("interface__isnull", True)),
                            models.Q(("cable__isnull", True), ("interface__isnull", False)),
                            _connector="OR",
                        ),
                        name="nso_linkrole_cable_xor_interface",
                    ),
                ],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
