# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Marcin Zieba
"""Vendor the observation components and their transitive schema references."""

import argparse
import copy
import json
from pathlib import Path

FAMILIES = frozenset(
    {
        "interface_attributes",
        "interface_ip",
        "lag_config",
        "lag",
        "bgp",
        "isis",
        "ospf",
        "redistribution",
        "route_policy",
        "vlan",
        "switchport",
        "interface_mtu",
        "svi",
        "subinterface",
        "bfd",
        "l2_service",
        "logging",
        "snmp",
        "static_route",
    }
)
VENDORED = Path(__file__).resolve().parents[1] / "netbox_nso_plugin/schemas/observations.json"


def _references(value):
    if isinstance(value, dict):
        if "$ref" in value:
            prefix = "#/components/schemas/"
            if not value["$ref"].startswith(prefix):
                raise ValueError(f"Unsupported schema reference: {value['$ref']}")
            yield value["$ref"][len(prefix) :]
        for child in value.values():
            yield from _references(child)
    elif isinstance(value, list):
        for child in value:
            yield from _references(child)


def _close_objects(value):
    if isinstance(value, dict):
        if value.get("type") == "object" and "properties" in value:
            value.setdefault("additionalProperties", False)
        for child in value.values():
            _close_objects(child)
    elif isinstance(value, list):
        for child in value:
            _close_objects(child)


def generate(snapshot):
    """Return deterministic JSON from an adapter OpenAPI snapshot."""
    schemas = json.loads(Path(snapshot).read_text(encoding="utf-8"))["components"]["schemas"]
    families = {
        schema["properties"]["family"]["const"]: name
        for name, schema in schemas.items()
        if name.endswith("ObservationOut") and schema["properties"]["family"]["const"] in FAMILIES
    }
    if set(families) != FAMILIES:
        raise ValueError(f"Missing observation families: {sorted(FAMILIES - families.keys())}")
    selected = {}
    pending = list(families.values())
    while pending:
        name = pending.pop()
        if name in selected:
            continue
        selected[name] = copy.deepcopy(schemas[name])
        pending.extend(_references(selected[name]))
    _close_objects(selected)
    return (
        json.dumps(
            {
                "$schema": "https://json-schema.org/draft/2020-12/schema",
                "$comment": "GENERATED by scripts/generate_observation_schemas.py from "
                "nso-adapter/tests/api/openapi_snapshot.json. Object properties are closed for publication. "
                "Do not edit this file.",
                "families": families,
                "components": {"schemas": selected},
            },
            sort_keys=True,
            indent=2,
        )
        + "\n"
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("snapshot", type=Path)
    parser.add_argument("--output", type=Path, default=VENDORED)
    args = parser.parse_args()
    rendered = generate(args.snapshot)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()
